// src/lib/components/Layout.svelte
<div class="layout"><slot /></div>

<style lang="scss">
	.layout {
		display: block;
		padding: 0 12px;
		@include responsive(max-width, min(100vw, 532px), $sm: unset);

		@include breakpoint(sm) {
			display: grid;
			grid-template-columns: 1fr 532px 1fr;
			grid-template-areas: 'left main right';
		}

		@include breakpoint(xl) {
			grid-template-columns: 1fr 612px 1fr;
		}

		@include breakpoint(xxxl) {
			grid-template-columns: 1fr 760px 1fr;
		}
	}
</style>

// src/components/Layout.tsx
import { ReactNode } from "react";

interface LayoutProps {
  children: ReactNode;
}

const Layout = ({ children }: LayoutProps) => {
  return (
    <div className="block px-3 sm:grid sm:grid-cols-[1fr_532px_1fr] sm:grid-template-areas-left-main-right 2xl:grid-cols-[1fr_612px_1fr] 3xl:grid-cols-[1fr_760px_1fr]">
      {children}
    </div>
  );
};

export default Layout;
