// src/lib/components/Sidebar.svelte
<script lang="ts">
	export let headings: any;
</script>

<div class="sidebar">
	<nav>
		{#each headings.filter((h) => h.level == 2) as heading}
			<a href={`#${heading.id}`}>{heading.text}</a>
		{/each}
	</nav>
</div>

<style lang="scss">
	.sidebar {
		display: none;

		@include breakpoint(md) {
			display: block;

			width: calc(50% - 300px);
			position: fixed;
			top: 28vh;
			left: 24px;
		}
	}

	nav {
		display: flex;
		flex-direction: column;
		gap: 12px;
		width: 157px;
		margin: auto;

		a {
			@include responsive(font-size, 15px, $xxl: 16px);
			line-height: 20px;
			color: var(--link-gray);
		}

		a:hover {
			border-bottom: none;
			color: var(--link-color);
		}
	}
</style>

// src/components/Sidebar.tsx
interface Heading {
  id: string;
  text: string;
  level: number;
}

interface SidebarProps {
  headings: Heading[];
}

const Sidebar = ({ headings }: SidebarProps) => {
  return (
    <div className="hidden md:block md:w-[calc(50%-300px)] md:fixed md:top-[28vh] md:left-6">
      <nav className="flex flex-col gap-3 w-[157px] mx-auto">
        {headings
          .filter((heading) => heading.level === 2)
          .map((heading) => (
            <a
              key={heading.id}
              href={`#${heading.id}`}
              className="text-[15px] 2xl:text-base leading-5 text-[var(--link-gray)] hover:text-[var(--link-color)] hover:no-underline"
            >
              {heading.text}
            </a>
          ))}
      </nav>
    </div>
  );
};

export default Sidebar;
